(() => {
 const deck = document.querySelector('.deck');
 const original = [...deck.querySelectorAll('.slide')];
 const notes = window.speakerNotes;
 const tbl = 'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/lag-1951649-om-straff-for-vissa-trafikbrott_sfs-1951-649/';
 const p5 = 'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/proposition/om-vissa-delegeringsfragor-och-regelforenkllngar_ga0334/html/';
 const p7 = 'https://www.riksdagen.se/sv/dokument-och-lagar/dokument/proposition/skarpta-regler-om-forverkande-av-fordon-vid_h20326/html/';
 const glossary = rows => '<div class="word-grid">' + rows.map(([term, explanation]) => `<details><summary>${term}</summary><p>${explanation}</p></details>`).join('') + '</div>';
 const create = (id, title, body, url, citation, spoken, instruction) => {
   const section = document.createElement('section');
   section.className = 'slide lesson';
   section.dataset.title = title;
   section.setAttribute('aria-labelledby', id);
   section.innerHTML = `<div class="slide-content"><p class="eyebrow">BG4 · innehåll, ordalydelse och syfte</p><h2 id="${id}">${title}</h2>${body}<p class="source-inline"><a href="${url}" target="_blank" rel="noreferrer">${citation}</a></p></div>`;
   return {section, note:['1–2 minuter', spoken, instruction]};
 };
 const law5 = create('law5','5 § · hela lagtexten', `<div class="law-text"><p>Om en vägtrafikant, som med eller utan skuld haft del i uppkomsten av en trafikolycka, genom att avlägsna sig från olycksplatsen undandrar sig att i mån av förmåga medverka till de åtgärder, vartill olyckan skäligen bör föranleda, eller om han undandrar sig att uppge namn och hemvist eller att lämna upplysningar om händelsen, döms till böter eller fängelse i högst sex månader.</p><p>Är brottet med hänsyn till omständigheterna att anse som grovt, döms till fängelse i högst ett år.</p><p>Bestämmelserna i första och andra styckena gäller även den som för spårvagn och den som annorstädes än på väg för motordrivet fordon.</p></div>`,tbl,'TBL 5 § · Lag (1986:1248)', 'Här ser vi hela femte paragrafen. Första stycket beskriver skyldigheterna och normalbrottets straffskala. Andra stycket gäller grovt brott. Tredje stycket utvidgar tillämpningen till spårvagnsförare och motordrivna fordon utanför väg. Vi går nu igenom orden.', 'Läs i lugn takt och peka ut de tre styckena. Förklara det äldre ordet annorstädes som någon annanstans.');
 const words5 = create('words5','5 § · vad betyder orden?',glossary([
 ['Vägtrafikant','Omfattar exempelvis bilförare, cyklister och gående. Personen måste ha haft del i olyckans uppkomst; att bara vara vittne på platsen räcker inte.'],
 ['Med eller utan skuld · haft del i uppkomsten','Deltagande i olycksförloppet krävs. Personen behöver däremot inte vara vållande eller ha orsakat olyckan genom ett brott. Även sakskadeolyckor omfattas.'],
 ['Undandrar sig · två alternativ','Det ena alternativet är att lämna platsen och därigenom undvika skäliga åtgärder. Det andra är att undanhålla identitet eller upplysningar; det kan ske även om personen stannar.'],
 ['I mån av förmåga · skäligen','Personens faktiska förmåga och olyckans omständigheter begränsar vad som krävs. Att varna, larma eller hjälpa kan behövas. Kraven är inte identiska vid alla olyckor.'],
 ['Namn och hemvist · upplysningar','Uppgifter om identitet, var personen hör hemma och händelsen. Identifieringen hjälper den skadelidande att kräva ersättning. RH 2022:2 visar hur uppgiftsskyldigheten bedöms i sitt sammanhang.'],
 ['Grovt brott · uppsåt','Allvarliga person- eller egendomsskador kan tala för grovt brott; helheten avgör. Uppsåt krävs enligt BrB 1:2 eftersom 5 § inte föreskriver oaktsamhetsansvar.']
 ]),tbl,'TBL 5 § · BrB 1:2 · NJA 2018 s. 394, p. 6–8 · RH 2022:2','Vi börjar med vem regeln gäller. Vållande krävs inte, men delaktighet i olycksförloppet gör det. Undandragande kan ske på två sätt. Skäligen och i mån av förmåga gör skyldigheten beroende av situationen. Uppsåt behövs även om ordet inte står i paragrafen.','Öppna uttrycken ett i taget och läs förklaringen med egna ord. Fråga klassen om en oskyldig cyklist kan omfattas. Svaret är ja om cyklisten haft del i olyckans uppkomst och övriga villkor är uppfyllda.');
 const purpose5 = create('purpose5','5 § · regelns syfte och utformning', `<div class="word-grid"><article><h3>Hjälp och identifiering efter olyckan</h3><p>Skyldigheten knyts till deltagandet i olyckan. HD beskriver identifieringen som viktig för den skadelidandes möjlighet att kräva ersättning.</p><p>NJA 2018 s. 394, p. 6–8: domstolens beskrivning av bestämmelsens funktion.</p></article><article><h3>Varför två svårhetsgrader?</h3><p>I förarbetet motiverades gradindelningen med att lindrigare fall skulle kunna hanteras genom strafföreläggande. Straffutrymmet för allvarliga fall behölls. Någon generell ändring av påföljdspraxis avsågs inte.</p><p>Prop. 1986/87:34, avsnitt 3.2, s. 10–11.</p></article></div>`,p5,'Förarbete till gradindelningen · prop. 1986/87:34','Skyldigheterna ska fungera efter en olycka även innan ansvaret för olyckan är avgjort. HD betonar att identifieringen möjliggör ersättningskrav. Förarbetet förklarar varför lagstiftaren delade upp brottet i två grader: enklare handläggning av lindrigare fall, med fortsatt utrymme för allvarliga fall.','Skilj mellan domstolens beskrivning av funktionen och lagstiftarens motiv till gradindelningen. Källorna står under respektive förklaring.');
 const law7 = create('law7','7 § · hela lagtexten', `<div class="law-text"><p>Ett fordon som har använts vid brott enligt denna lag får förklaras förverkat, om det behövs för att förebygga fortsatt sådan brottslighet och förverkande inte är uppenbart oskäligt. Detsamma gäller annan egendom som har använts som hjälpmedel vid brott enligt denna lag.</p><p>Om någon har gjort sig skyldig till olovlig körning, rattfylleri eller grovt rattfylleri ska det vid bedömningen av om förverkande behövs för att förebygga fortsatt brottslighet särskilt beaktas om gärningsmannen tidigare har gjort sig skyldig till sådan brottslighet.</p><p>Första stycket gäller även i fråga om egendom som varit avsedd att användas som hjälpmedel vid brott enligt denna lag, om brottet har fullbordats.</p><p>Bestämmelser om tillfälligt omhändertagande av egendom i syfte att förhindra rattfylleribrott finns i 24 a-24 d §§ polislagen (1984:387), 3 kap. 16 a och 16 b §§ kustbevakningslagen (2019:32) och 10 kap. 1-3 §§ tullbefogenhetslagen (2024:710).</p></div>`,tbl,'TBL 7 § · Lag (2024:715)','Sjunde paragrafen har fyra stycken. Först grundvillkoren. Sedan den särskilda vikten av tidigare brott. Tredje stycket gäller avsedda hjälpmedel när brottet fullbordats. Det sista hänvisar till andra regler om tillfälligt omhändertagande för att förhindra rattfylleri.','Visa hela texten. Rulla vid behov. Förverkande är en särskild rättsverkan; tillfälligt omhändertagande enligt hänvisningarna är en annan åtgärd.');
 const words7 = create('words7','7 § · vad betyder orden?',glossary([
 ['Får förklaras förverkat','Egendomen kan fråntas ägaren som särskild rättsverkan. Det kräver en prövning av villkoren och sker inte automatiskt vid varje trafikbrott.'],
 ['Använts vid brott enligt denna lag','Koppling till brott enligt just trafikbrottslagen krävs. En förseelse enligt en annan trafikförfattning räcker inte i sig för 7 §.'],
 ['Behövs för att förebygga fortsatt sådan brottslighet','En framåtblickande bedömning av risken för fortsatta TBL-brott. Det förebyggande behovet måste kunna motiveras.'],
 ['Särskilt beaktas','Tidigare olovlig körning och rattfylleribrott ges särskild vikt enligt andra stycket. Det är ingen automatisk regel om ett visst antal brott.'],
 ['Inte uppenbart oskäligt','En hög tröskel för att avstå när övriga villkor är uppfyllda. Helheten prövas, inklusive ekonomiska förhållanden och andra personers behov. Ett högt fordonsvärde avgör inte ensamt.'],
 ['Annan egendom · avsedd att användas','Även andra hjälpmedel omfattas. Ett avsett hjälpmedel kan omfattas om brottet fullbordats; tredje stycket är inte en generell regel om förverkande vid försöksbrott.']
 ]),p7,'TBL 7 § · prop. 2014/15:26, avsnitt 5.1 och s. 28–30','Lägg märke till orden får och behövs. Ett begånget brott ger inte ett automatiskt förverkande. Tidigare brott väger särskilt tungt, men vi måste fortfarande bedöma helheten. Uppenbart oskäligt innebär en hög tröskel för att avstå.','Öppna uttrycken i ordning. Förklara förverkat med vardagliga ord. Knyt varje ord till vilken uppgift en domstol behöver.');
 const purpose7 = create('purpose7','7 § · lagstiftarens avsikt',`<div class="word-grid"><article><h3>Motverka upprepade trafikbrott</h3><p>Förverkandet ska minska möjligheten att fortsätta begå trafikbrott. År 2015 tydliggjordes betydelsen av tidigare olovlig körning och rattfylleribrott.</p></article><article><h3>Från oskäligt till uppenbart oskäligt</h3><p>Lagändringen skulle göra förverkande möjligt i fler fall. Starkare skäl krävs för att avstå, samtidigt som en individuell bedömning finns kvar.</p></article></div><p class="takeaway">De två hovrättsfallen är från 2020 och 2022, efter skärpningen 2015. De visar behovs- och skälighetsbedömningen, inte fasta beloppsgränser.</p>`,p7,'Prop. 2014/15:26, avsnitt 5.1 och författningskommentaren','Lagstiftaren ville få större genomslag för förverkande vid upprepad trafikbrottslighet. Därför betonades återfall och gränsen ändrades till uppenbart oskäligt. Det förklarar varför även dyr egendom kan förverkas men varför en prövning fortfarande måste göras.','Visa rättsfallen efter denna förklaring. Påminn om att hovrättsfall illustrerar tillämpningen men inte är HD-prejudikat.');
 law7.section.querySelector('.law-text').insertAdjacentHTML('afterend', `<details class="pl-explanation"><summary>Hänvisningen i 7 §: PL 24 a–24 d §§ – vad innebär den?</summary><p><strong>Förhindra rattfylleri nu – inte förverka egendom.</strong> Hänvisningen finns i 7 § TBL, inte i 5 §.</p><dl><dt>24 a § · Ingripandet</dt><dd>Särskilda skäl ska tala för risk för rattfylleri eller grovt rattfylleri. Polisen får tillfälligt ta nycklar, annat som behövs för färden eller vid behov fordonet. Nödvändig kroppsvisitation och genomsökning av fordonet får göras för att hitta egendomen.</dd><dt>24 b § · Kontroll</dt><dd>Beslutet anmäls skyndsamt till förmannen, som omedelbart prövar om åtgärden ska fortsätta.</dd><dt>24 c § · Slut och återlämnande</dt><dd>Åtgärden upphör när skälen försvinner, senast efter 24 timmar. Egendomen återlämnas till den den togs från, om inte särskilda skäl talar för någon annan.</dd><dt>24 d § · Ohämtad egendom</dt><dd>Försäljning eller förstöring kräver villkoren i lag (1974:1066). Berörda ska delges underrättelse; det sker inte automatiskt efter 24 timmar.</dd></dl><p><strong>Kom ihåg:</strong> PL = tillfällig förebyggande åtgärd. TBL 7 § = förverkande med egen prövning.</p><a href="https://www.riksdagen.se/sv/dokument-och-lagar/dokument/svensk-forfattningssamling/polislag-1984387_sfs-1984-387/" target="_blank" rel="noreferrer">Läs polislagen hos Riksdagen · kontrollerat 11 september 2026</a></details>`);
 law7.note[1] += ' Hänvisningen gäller polislagen. Om särskilda skäl visar risk för rattfylleri kan polisen tillfälligt ta exempelvis nycklarna. Förmannen ska pröva beslutet direkt. Åtgärden upphör när skälen försvinner och får vara högst 24 timmar. Det är inte samma sak som förverkande.';
 law7.note[2] += ' Öppna rutan om PL 24 a–24 d §§ och avsätt cirka 45 sekunder. Betona: 24 timmar är en maxgräns, inte en standardtid. Ohämtad egendom blir inte automatiskt förverkad.';
 const order = [0,1,law5,words5,purpose5,3,2,4,law7,words7,purpose7,6,7,9,8];
 deck.replaceChildren(...order.map(item=>typeof item==='number'?original[item]:item.section));
 window.speakerNotes = order.map(item=>typeof item==='number'?notes[item]:item.note);
 window.speakerNotes[0] = ['30 sekunder','Vi är basgrupp 4. Vi ska redovisa femte och sjunde paragrafen i trafikbrottslagen. För varje paragraf går vi igenom innehållet, ordalydelsen och syftet. Därefter visar vi hur domstolarna har tolkat lagen.','Fördela avsnitten före seminariet. Räkna preliminärt med 18–22 minuter och anpassa till lärarens tidsram.'];
 window.speakerNotes[13][2] = 'Sammanfatta innehåll, ordalydelse och rättsfall. Därefter finns en frivillig bevisövning om tiden räcker. Uppgiften anger ingen tidsgräns.';
 window.speakerNotes[14][0] = 'Frivillig repetition · cirka 2 minuter';
 original[8].dataset.title = 'Frivillig bevisutmaning';
 original[8].querySelector('.eyebrow').textContent = 'Frivillig repetition efter redovisningen';
 original[9].querySelector('[data-action="restart"]').textContent = 'Börja om redovisningen';
 document.querySelector('.slide-meta').textContent = 'Lagtext · ordalydelse · syfte · modern praxis · kontrollerat 9 september 2026';
})();
