window.speakerNotes = [
  ['30 sekunder', 'Vi är basgrupp 4: Johan Stensson, Fredrik Karlsson, Vegard Lein och Dennis Vessman. Vi ska prata om vad som krävs efter en trafikolycka och när ett fordon kan förverkas.', 'Starta och gå vidare. Klassen får rösta med handuppräckning.'],
  ['45 sekunder', 'Femte paragrafen handlar om personens agerande efter olyckan. Sjunde paragrafen handlar om att förebygga fortsatt trafikbrottslighet genom förverkande. Vi börjar på olycksplatsen.', 'Peka på skillnaden mellan straffbestämmelse och särskild rättsverkan.'],
  ['1 minut 15 sekunder', 'I det verkliga fallet körde en bilförare in i en vägskylt och sprang därifrån. Han åtalades också för bland annat grovt rattfylleri och grov olovlig körning. Frågan i HD var om smitningsansvar stred mot rätten att inte belasta sig själv. Vad tror ni?', 'Läs frågan. Låt klassen rösta och klicka sedan. Förklara: HD dömde för smitning. Avgörandet gäller den här sakskadesituationen, inte en obegränsad skyldighet att erkänna brott. Källa: NJA 2018 s. 394, dom 12 juni 2018.'],
  ['1 minut 30 sekunder', 'Vi behöver en trafikolycka och en person som haft del i uppkomsten. Personen behöver inte ha varit vållande. Sedan måste vi visa vad personen undandrog sig. Det kan handla om att lämna platsen och därigenom undvika skäliga åtgärder, eller om att hålla inne uppgifter. Vad situationen kräver beror på skadan, faran och personens förmåga. Slutligen krävs uppsåt.', 'Klicka fram ett rekvisit i taget i huvudfönstret. Förklara rekvisit som villkor som måste vara uppfyllda. Nämn straffskalan kort.'],
  ['1 minut 15 sekunder', 'I det här fallet erbjöd motorcykelföraren sitt personliga telefonnummer. Ungdomarna var 15 och 16 år, ingen blev allvarligt skadad och de frågade inte efter fler uppgifter. Blev han dömd eller friad?', 'Låt klassen rösta. Visa sedan svaret. Hovrätten friade, men ett telefonnummer räcker inte alltid. Åtalets utformning begränsade prövningen till uppgiftsskyldigheten. Huvudprincipen är att självmant upplysa om sin identitet. Källa: RH 2022:2.'],
  ['45 sekunder', 'Nu byter vi fråga. Det här är ett påhittat diskussionsunderlag, inte en dom. Bilen används vid upprepad trafikbrottslighet men familjen säger att den behövs. Vilka uppgifter saknar vi?', 'Ta två förslag. Klicka på ett alternativ. Alla val leder till samma diskussion: vi behöver ett mer komplett underlag.'],
  ['1 minut 15 sekunder', 'Först behöver vi en koppling mellan egendomen och ett brott enligt trafikbrottslagen. Sedan frågar vi om förverkandet behövs för att förebygga nya brott. Tidigare olovlig körning och rattfylleribrott ska beaktas särskilt. Till sist bedömer vi om förverkandet skulle vara uppenbart oskäligt. Vi måste också utreda vem egendomen faktiskt tillhör.', 'Öppna de tre rutorna i huvudfönstret. Förklara att bilens värde eller registreringen ensamt inte avgör saken.'],
  ['1 minut 15 sekunder', 'Här är två verkliga hovrättsfall. I fall A handlade det om mycket omfattande trafikbrottslighet och tillgång till andra traktorer. I fall B hade föraren mycket svag ekonomi och en outredd kreditfråga. Hur tror ni att domstolen bedömde dem?', 'Visa utgången efter varje gissning. Båda fordonen förverkades i A. I B ansågs förverkande uppenbart oskäligt. Fallen återges i Åklagarmyndighetens vägledning, sidorna 23–24. De visar helhetsbedömningar, inga fasta beloppsgränser.'],
  ['1 minut 30 sekunder', 'Nu kopplar vi reglerna till polisens arbete. Vilken utredning hör varje uppgift främst till: femte paragrafen, sjunde eller båda?', 'Klicka på klassens svar. Läs förklaringen vid behov. Sju frågor tar cirka 90 sekunder i snabbt tempo; avsätt längre tid om ni vill diskutera. Återställ svar börjar om övningen.'],
  ['45 sekunder', 'Ta med er två frågor. Vad undandrog sig personen efter olyckan? Och behöver egendomen förverkas för att förebygga nya trafikbrott? Underlaget måste visa både skälen för åtgärden och motstående omständigheter. Beslag säkrar egendomen under utredningen. Förverkande är den slutliga rättsföljden.', 'Avsluta och ta frågor. Planerad tal- och övningstid totalt: cirka 11 minuter. Utskriftsknappen ger klassen en kort sammanfattning.']
];
